### ISSUE TITLE
License problem: Hypothesis is MPL-2.0, and this should be too.

### ISSUE THREAD

**Issue by Zac-HD** [python-trio/hypothesis-trio#2]
The MPL-2.0 is basically a per-file copyleft, akin to the LGPL or a GPL without the linking clause.  Because this library is basically an async-capable port of `hypothesis.stateful`, it must also be MPL licensed.

@touilleMan @njsmith is there an existing process for this, or should I just change the license files and setup.py?  More importantly, how to we make sure Trio projects get licensing right in future?

**Comment by njsmith** [comment]
I guess the process is:

* @touilleMan and any other contributors have to agree to re-license their contributions. (The MPL can't force them to release their code under a matching license; all it can do is forbid us to distribute it under an incompatible license.) Can you check `git log` to make sure we know who exactly we need to talk to?

* Then we go ahead and change the license files and setup.py

> how to we make sure Trio projects get licensing right in future?

I don't really have any brilliant suggestions here. I don't think we have resources to, like, use automated scans to detect license non-compliance or anything. And this project's been kind of off in a corner without as much attention as some other ones. (I have to admit I still don't really understand hypothesis's stateful testing :cold_sweat:.) Most projects seem to get by with just... noticing things like this as they come up? I know that's not very satisfying though :-/

**Comment by touilleMan** [comment]
>     * @touilleMan and any other contributors have to agree to re-license their contributions

According to https://github.com/python-trio/hypothesis-trio/graphs/contributors, only me, @Zac-HD  and @vxgmichel have commited on this project.

I'm totally ok to change the license, so we only need @vxgmichel approval ;-)

**Comment by vxgmichel** [comment]
>     * @touilleMan and any other contributors have to agree to re-license their contributions.

Yey, copyleft! Agreed :+1:

**Comment by Zac-HD** [comment]
Awesome - I'll make and merge a PR for that when I get home 😄

**Comment by Zac-HD** [comment]
@touilleMan - all done!  Can you make a release?

**Comment by njsmith** [comment]
@Zac-HD Hey, what's your PyPI username? :-)

**Comment by Zac-HD** [comment]
Why, it's [Zac-HD](https://pypi.org/user/Zac-HD/) 😜

**Comment by njsmith** [comment]
@Zac-HD oh hey look: https://pypi.org/project/hypothesis-trio/

**Comment by Zac-HD** [comment]
🎉 

Any trick to cutting releases, beyond the usual towncrier-setup.py-twine sequence?

**Comment by njsmith** [comment]
I'm not aware of any...

**Comment by Zac-HD** [comment]
Haha, turns out that I had a `~/.pypirc` with the legacy URL... deleted that line and everything worked :shipit:

**Comment by touilleMan** [comment]
@Zac-HD It seems you have forgotten to correct the `License: Your choice of MIT or Apache License 2.0` part of the README

**Comment by njsmith** [comment]
Your release automation makes you soft!

I'm envious :-(

I wish wish wish any of these CI platforms had some simple way to keep deploy secrets from people with commit access :-(.

**Comment by njsmith** [comment]
Whoops, the curse of direct pushing strikes again.

Well, at least it pointed out we had branch protection turned off :-). I just turned it on.
